services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file: ./.env.docker
    volumes:
      - ./apps/api/app:/app/app
    ports:
      - "${API_PORT_EXTERNAL:-8000}:8000"
    depends_on:
      - db
      - redis
      - chroma
      - mongo
      - minio
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web-student:
    build:
      context: ./apps/web-student
      dockerfile: Dockerfile
    env_file: ./.env.docker
    volumes:
      - ./apps/web-student/src:/app/src:cached
      - ./apps/web-student/public:/app/public:cached
    ports:
      - "${WEB_STUDENT_PORT_EXTERNAL:-5173}:5173"
    depends_on:
      - api

  web-admin:
    build:
      context: ./apps/web-admin
      dockerfile: Dockerfile
    env_file: ./.env.docker
    volumes:
      - ./apps/web-admin/src:/app/src:cached
    ports:
      - "${WEB_ADMIN_PORT_EXTERNAL:-5174}:5173"
    depends_on:
      - api

  db:
    image: postgres:17.6
    env_file: ./.env.docker
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - smartfaq-db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT_EXTERNAL:-5432}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT_EXTERNAL:-6379}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  chroma:
    image: chromadb/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - "${CHROMA_PORT_EXTERNAL:-8001}:8000"

  mongo:
    image: mongo:7.0
    env_file: ./.env.docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-smartfaq}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-smartfaq}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-smartfaq}
    volumes:
      - mongo-data:/data/db
    ports:
      - "${MONGO_PORT_EXTERNAL:-27017}:27017"
    command: ["--bind_ip_all"]

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  create_minio_bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        mc mb -p myminio/${MINIO_BUCKET};
        exit 0;
      "

volumes:
  smartfaq-db:
  redis-data:
  chroma-data:
  mongo-data:
  minio-data: