services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file: ./.env.docker
    volumes:
      - ./apps/api/app:/app/app
    ports:
      - "${API_PORT_EXTERNAL:-8000}:8000"
    depends_on:
      - db
      - redis
      - chroma
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web-student:
    build:
      context: ./
      dockerfile: apps/web-student/Dockerfile
    env_file: ./.env.docker
    volumes:
      - ./apps/web-student/src:/workspace/apps/web-student/src
      - ./packages/ui/src:/workspace/packages/ui/src
    ports:
      - "${WEB_STUDENT_PORT_EXTERNAL:-5173}:5173"
    depends_on:
      - api

  web-admin:
    build:
      context: ./
      dockerfile: apps/web-admin/Dockerfile
    env_file: ./.env.docker
    ports:
      - "${WEB_ADMIN_PORT_EXTERNAL:-5174}:5173"
    depends_on:
      - api
    develop:
      watch:
        - path: ./apps/web-admin/src
          action: sync
          target: /workspace/apps/web-admin/src
        - path: ./packages/ui/src
          action: sync
          target: /workspace/packages/ui/src
        - path: ./apps/web-admin/package.json
          action: rebuild


  db:
    image: postgres:17.6
    env_file: ./.env.docker
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - smartfaq-db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT_EXTERNAL:-5432}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT_EXTERNAL:-6379}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  chroma:
    image: chromadb/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - "${CHROMA_PORT_EXTERNAL:-8001}:8000"

volumes:
  smartfaq-db:
  redis-data:
  chroma-data:
