apiVersion: v2
name: redis-smartfaq
description: A Helm chart for Redis
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: 23.2.12
    repository: oci://registry-1.docker.io/bitnamicharts
