apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartfaq-celery-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: celery-worker
          image: asia-southeast1-docker.pkg.dev/enspara/smartfaq/smartfaq-api:dev-latest
          command:
            - python
            - -m
            - celery
            - -A
            - app.workers
            - worker
            - --loglevel=info
            - --concurrency=1
          resources:
            requests:
              memory: 1.5Gi
              cpu: "500m"
            limits:
              memory: 2.5Gi
              cpu: "1.5"
