apiVersion: v2
name: postgres-smartfaq
description: A Helm chart for PostgreSQL service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 18.1.10
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
