apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smartfaq-dev-tls
  namespace: smartfaq-dev
spec:
  secretName: smartfaq-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.smartfaq.dev.devplus.edu.vn
  privateKey:
    algorithm: RSA
    size: 2048
