apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - statefulSet.yaml
  - service.yaml
  - ingress.yaml
  - network-policy.yaml
  - resource-quota.yaml
  - chroma.yaml
  - minio.yaml
  # - celery-worker.yaml  # TODO: Enable when Celery is implemented
