apiVersion: v1
kind: ResourceQuota
metadata:
  name: smartfaq-api-quota
spec:
  hard:
    requests.cpu: "25"
    requests.memory: 24Gi
    limits.cpu: "30"
    limits.memory: 40Gi
    persistentvolumeclaims: "15"
    pods: "15"
    services: "10"
    secrets: "15"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: smartfaq-api-limits
spec:
  limits:
    - default:
        cpu: "2"
        memory: 2Gi
      defaultRequest:
        cpu: "100m"
        memory: 256Mi
      type: Container
    - max:
        storage: 50Gi
      min:
        storage: 1Gi
      type: PersistentVolumeClaim
